# fly.toml app configuration file generated for news-ai-yagebin on 2025-04-03T17:00:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'news-ai-yagebin'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8085
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '1m0s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[services]]
  protocol = 'tcp'
  internal_port = 8085
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '1m0s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
