# fly.toml app configuration file generated for news-ai-yagebin on 2025-03-23T13:40:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'news-ai-yagebin'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8083
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
