# fly.toml app configuration file generated for news-ai-yagebin on 2025-03-23T13:40:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'news-ai-yagebin'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8083
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  # Base URL route (subscriber management)
  [[http_service.routes]]
    path = "/"
    handlers = ["http"]
    port = 8083

  # Newsletter viewing route
  [[http_service.routes]]
    path = "/newsletter/*"
    handlers = ["http"]
    port = 8085

[[services]]
  protocol = "tcp"
  internal_port = 8083
  processes = ["app"]

  [[services.ports]]
    port = 8083
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 8085
  processes = ["app"]

  [[services.ports]]
    port = 8085
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
