# fly.toml app configuration file generated for news-ai-yagebin on 2025-03-23T13:40:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'news-ai-yagebin'
primary_region = 'fra'

[build]

[http_service]
  # This should match the port Nginx is listening on (8085)
  internal_port = 8085
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  
  # Configure health checks
  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200
  
  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "120s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[services]]
  http_checks = []
  internal_port = 8085
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "120s"
    interval = "30s"
    restart_limit = 0
    timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
